# Page settings

baseURL = "https://benchi.netlify.app"
languageCode = "en"
title = "Benchi Philipose" 
theme = "dev"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "Benchi Philipose"
    description = "My Resume"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Benchi Philipose"
        tagline = "Sales & Marketing Professional"







    [params.contact]
        enable = true
        location = "Bangalore, India"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+91 9900966665"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "benchiphilipose@rediffmail.com"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Energy Monitoring Systems & Software "
        [[params.skills.list.items]]
        details = "Energy Efficiency Solutions Sales"
        [[params.skills.list.items]]
        details = "Power Quality Solutions"
        [[params.skills.list.items]]
        details = "Electrical Panel Components"
        
        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective Communication"
        [[params.skills.list.items]]
        details = "Team Play & Team Management"
        [[params.skills.list.items]]
        details = "Strong Problem Solving"
        [[params.skills.list.items]]
        details = "Key Account / Channel Management"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "EMBA in Marketing"
        university = "Karnataka State Open University "
        
        [[params.education.list]]
        degree = "BE in Electrical & Electronics Engineering"
        university = "Bangalore University"

        [[params.education.list]]
        degree = "Pre Degree Course in PCM"
        university = "Kerala University"







    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Best Regional Manager Award "
        body = "Schneider Electric"
        date = "2007 & 2011"
        [[params.awards.list]]
        name = "Best Dealer Motivator Award"
        body = "Conserv Systems"
        date = "2002 & 2003"
        [[params.awards.list]]
        name = "Best Team Player Award"
        body = "Conserv Systems"
        date = "2004 & 2005"
        [[params.awards.list]]
        name = "POSE Value Champion Award"
        body = "Schneider Electric"
        date = "2010 & 2011"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "----"
        [[params.languages.list]]
        name = "Hindi"
        level = "---"
       [[params.languages.list]]
        name = "Tamil"
        level = "---"
        [[params.languages.list]]
        name = "Kannada"
        level = "--"
        [[params.languages.list]]
        name = "Malayalam"
        level = "----"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Reading"
        [[params.interests.list]]
        name = "Swimming"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = "Dedicated Professional with 25 years of experience in Sales, Marketing, Business Development, Key Account Management, Distribution / Channel Partner Management, Branch management and People Development in multifarious industry spectrum."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Associate Vice President - Business Development"
        dates = "Feb 2024 – Present"
        company = "Elecroom Technologies. Bangalore, India"
        details = "Leading the business development activites for major brands like EAPL, Delixi Electric, Dewon Electric, Relicell Battery, etc."

        [[params.experience.list]]
        title = "Director – Business Development"
        dates = "Jan 2021 - Jan 2024"
        company = "Urja Power And Building Automation. Bangalore, India"
        details = "Developing periodic business plans & strategies, in coordination with macro plans of organization for revenue generation through sales for a division deal with Energy Monitoring & Power Quality Solutions and Services."

        [[params.experience.list]]
        title = "Associate General Manager – Business Development"
        dates = "Jul 2015 – Dec 2019"
        company = "Schneider Electric. Mumbai, India"
        details = "Managed the business through Distributors & Direct in collaboration with national sales team, as per the need of Power Solutions business unit, a division deal with Metering, Energy Monitoring Software, Energy Audit, Energy Efficiency Solutions, Capacitors, APFC Panels, Harmonic filters, etc. Made Area Specific Strategy, Ensured Implementation & Generation of New Business. Monitored the Performance monthly and fine-tuned strategies as and when required, to ensure healthy growth from each region. Focused on Solution Sales and Ensured Specific Effort at End Customer from influencer level to CXO level."

        [[params.experience.list]]
        title = " Associate General Manager – Customer Marketing"
        dates = "Jan 2012 – Jun 2015"
        company = " Schneider Electric. Bangalore, India "
        details = " Updated and Refreshed Panel Builder (PB)Channel Strategy / Road Map, Lead the effort in strengthening relationship with Partners / Key Panel Builders, Maintained close relationship at PB’s CEO / owners’ level and Deployed the loyalty program for the partners. "

        [[params.experience.list]]
        title = "Regional Manager – Sales & Support"
        dates = "Apr 2008 – Dec 2011"
        company = " Schneider Electric. Bangalore, India "
        details = "Handled a team of 30 with less than 5% Attrition to manage / achieve the business targets set by Energy Management Business Unit in Sales, Revenue, Customer Satisfaction and Marketing Events. "

        [[params.experience.list]]
        title = "Area Manager – Sales & Support"
        dates = "Jan 1999 -Mar 2008"
        company = "Schneider Electric (Formerly Conzerv Systems).  Cochin / Coimbatore, India"
        details = " Effectively handled the area as a profit center and achieved revenue, market share, profitability growth and handled the dealer network / developed relationships with different industrial segments. Tracked the productivity of the company engineers & the distributor’s engineers. Positioned the metering and power solution software products in premium segments. Conducted seminars, demonstrations, presentations for various forums etc. "

        [[params.experience.list]]
        title = "Territory Manager – Sales & Support"
        dates = "Jul 1995 – Dec 1998"
        company = "Supratronics Systems. Calicut, India"
        details = " Business Development with Major computer dealers, End Customers, and traders to increase the reach and Business of Power Conditioning Equipment’s like UPS, Stabilizers etc. Successfully coordinated with factory for effective SCM and allocation of material to assure timely delivery of order."





    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//www.linkedin.com/in/benchi-philipose-929a0486/"
        title = "Linkedin"

    [params.footer]
        copyright = ""
